### ISSUE TITLE
The app takes double the disk space due to improper cleanup

### ISSUE THREAD

**Issue by Ketok4321** [flathub/io.gitlab.adhami3310.Footage#2]
The files `lib/gstreamer-1.0/libgstgif.a` and `lib/gstreamer-1.0/libgstgtk4.a` take about 116MB of disk space in the final build.
As far as I'm aware they're only compile-time dependencies and therefore should probably be cleaned up.

**Comment by adhami3310** [comment]
Those both seem to be the files necessary for gstreamer to encode in GIF and to have a paintable GTK4 component. They are both necessary for the app. Or is the .a file extension not important but the .s one is? Please let me know more on how to confirm this.

**Comment by Ketok4321** [comment]
Aren't `.a` libraries supposed to be statically linked?
The cleanup of this project is already configured to remove `/lib/*.a`, hovewer those two are omitted because they're inside a subdirectory.
Also, from what I tried, exporting gifs seems to work fine after manually removing them.
I might be wrong tho, I don't have that much experience in low level programming (or really programming at all).

**Comment by adhami3310** [comment]
I will give it a try next update. Thank you so much for catching this :D

**Comment by adhami3310** [comment]
It's gotten much better with new fix! :D
